### ISSUE TITLE
SHIT THAT NEEDS FIXING ASAP

### ISSUE THREAD

**Issue by williamwu0013** [LendingGuys/StatedIncome#26]
- MISSING NO. MONTHS 1003 PART 1
- NEED OWN OR RENT BOX IN 1003 PART 3
- NEED MARITALSTATUS BOX IN 1003 PART 3
- NEED SELF EMPLOYED FIELD IN 1003 PART 4
- NEED MONTHLY INCOME IN 1003 PART 4
- ENTIRE JSON FOR 1003 6A IS NIL
- MISSING FIELDS FOR 1003 PART 6
- NEED REST OF FORMS FOR PART 1003 PART 8
- FORM 10 HAS NONE OF THE QUESTIONS

- APPRAISAL IS SPELLED WRONG IN ARCHIVE. IS THIS OKAY? APPRASIAL.
- YELLOW HAMMER JSON DOES NOT SEEM TO WORK.
- REDO INCOME QUALIFICATION FORM - LANDSCAPE ISSUES

- NEED STATE FOR DRIVER'S LICENSE

**Comment by klam8564** [comment]
MISSING NO. MONTHS 1003 PART 1
APPARENTLY THERE
NEED OWN OR RENT BOX IN 1003 PART 3
NEED MARITALSTATUS BOX IN 1003 PART 3
NEED SELF EMPLOYED BOX IN 1003 PART 4
NEED MONTHLY INCOME IN 1003 PART 4
ENTIRE JSON FOR 1003 6A IS NIL
MISSING FIELDS FOR 1003 PART 6
NEED REST OF FORMS FOR PART M 1003 PART 8
FORM 10 HAS NONE OF THE QUESTIONS

APPRAISAL IS SPELLED WRONG IN ARCHIVE. IS THIS OKAY? APPRASIAL.

YELLOW HAMMER JSON DOES NOT SEEM TO WORK.

REDO INCOME QUALIFICATION FORM - LANDSCAPE ISSUES
